In [1]:
import numpy as np

In [2]:
filename = '001_ServoCurveData_0000.nta'

f = open(filename,'r')

lines = f.readlines()

In [3]:
lines[:30]

['%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n',
 '%%    Created by Servo Tracker 4.0 \n',
 '%%    2010-10-12 15:33:49\n',
 '%%    SW Compilation date and time: Jan 15 2009 15:53:31\n',
 '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n',
 '% Data logged using the program version shown below\n',
 '% Application Name: Servo Tracker\n',
 '% Version: 4.0 \n',
 '% Build: Jan 15 2009 / 15:53:31\n',
 '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n',
 '% Data logged from Servo-i hw/sw as shown below\n',
 '% Servo-i,004,-,001\n',
 '% Breathing system: 18.14.00\n',
 '% Monitoring: 18.14.01\n',
 '% Panel: 18.14.00\n',
 '% ExpFlowMeter: 18.14.00\n',
 '% CIE: 18.14.01\n',
 '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n',
 '% Reference Time, Servo-i: 2010/10/11 14:40:03 PC: 2010/10/11 15:42:41\n',
 '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n',
 '

#### Prendiamo solo le line che non iniziano con % e ognuna la dividiamo in 8 usando il tab come delimitatore, togliendo il newline al fine riga.

In [4]:
data = []
for line in lines:
    if not line.startswith('%'):
        data.append(line.replace('\n','').split('\t',8))

In [7]:
np.shape(data)

(65472, 8)

#### Codice per trasformare i dati in un array di float tenendo solo le colonne dalla posizione 4 alla 7 comprese.

In [5]:
v = np.ndarray(shape=(len(data),4),dtype=float)
for i in range(len(data)):
    for j in range(3,7):

        v[i-3,j-3]=float(data[i][j])

In [6]:
np.shape(v)

(65472, 4)

#### Ora dobbiamo dividere i singoli atti respiratori sfruttando la prima colonna composta di 0 e 1. 0 e' inspirio 1 e' espirio. Quindi quando si passa da 1 a 0 si deve dividere la sequenza.

In [16]:
x = [0,0,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,1,0]

In [34]:
np.diff(x)

array([ 0,  0,  0,  0,  1,  0,  0,  0,  0, -1,  0,  0,  1,  0,  0,  0, -1,
        0,  0,  0,  0,  0,  0,  0,  1, -1])

In [35]:
np.diff(x) == 1

array([False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False,  True, False], dtype=bool)

#### Con la funzione numpy ```nonzero``` [Numpy nonzero](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.nonzero.html) otteniamo la lista degli indici nei quali l'array non e' zero.

In [37]:
np.nonzero(np.diff(x) == 1)

(array([ 4, 12, 24]),)

#### L'output e' un po' strano quindi prendiamo il primo elemento che e' esattament el'array richiesto

In [40]:
np.nonzero(np.diff(x) == 1)[0]

array([ 4, 12, 24])

#### E spostiamo a destra di una posizione per ottenere le esatte posizioni nelle quali abbiamo il cambio da 1 a 0.

In [39]:
np.nonzero(np.diff(x) == 1)[0] + 1

array([ 5, 13, 25])

In [32]:
np.split(x, np.nonzero(np.diff(x) == 1)[0]+1)

[array([0, 0, 0, 0, 0]),
 array([1, 1, 1, 1, 1, 0, 0, 0]),
 array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0])]

#### Ovviamente una volta che abbiamo gli indici possiamo splittare qualsiasi array .

In [ ]:
def build_data(v):
    length = len(v)
    st = v[:,0] # Stato 0 inspirio - Stato 1 espirio
    pr = v[:,1] # Pressione
    fl = v[:,2] # Flusso
    ed = v[:,3] # EaDI

    
    d.append(l)
    return d

In [47]:
index = np.nonzero(np.diff(v[:,0])==1)[0]+1
index

array([  435,   850,  1292,  1635,  2049,  2478,  2906,  3740,  4168,
        4538,  5312,  5740,  6182,  6611,  7039,  7468,  7841,  8272,
        8754,  9182,  9611, 10040, 10468, 10880, 11325, 11755, 12149,
       12547, 12888, 13248, 13625, 14025, 14406, 14831, 15221, 15534,
       15954, 16287, 16607, 16991, 17368, 17754, 18183, 18512, 18907,
       19336, 19731, 20154, 20574, 21004, 21425, 21887, 22197, 22546,
       22985, 23457, 23923, 24285, 24744, 25147, 25501, 25819, 26194,
       26589, 26960, 27347, 27711, 28085, 28469, 28858, 29271, 29665,
       30037, 30410, 30864, 31198, 31475, 31777, 32125, 32558, 32981,
       33391, 33717, 34063, 34401, 34829, 35266, 35697, 36038, 36447,
       36825, 37173, 37562, 37966, 38328, 38687, 39125, 39468, 39910,
       40253, 40665, 41099, 41418, 41800, 42184, 42605, 42976, 43348,
       43747, 44100, 44461, 44802, 45123, 45428, 45769, 46206, 46612,
       46954, 47276, 47610, 47933, 48293, 48666, 49036, 49431, 49855,
       50321, 50669,

In [50]:
np.split(v[:1000,0],index)

[array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.